### ISSUE TITLE
Front-end work for Portfolio

### ISSUE THREAD

**Issue by stevengoldbergm** [stevengoldbergm/portfolio#1]
**Description**
I need to complete the following tasks before launching the site 

**Tasks**

- [x] Design basic user interface
- [x] Style site utilizing sourced stock images
- [x] Link contact form to external database
- [ ] Set up notification system for contact form

**Comment by stevengoldbergm** [comment]
Basic user interface is complete, and an external database has been set to house contact data.
