### ISSUE TITLE
Style site utilizing sourced stock images

### ISSUE THREAD

**Issue by stevengoldbergm** [stevengoldbergm/portfolio#3]
**Description**
Make the site look more appealing to visitors

**Tasks**
- [x] Source images for the finished site
- [x] Create a color scheme that matches existing stock images
- [ ] Add animations/transitions utilizing appropriate NPM packages
- [ ] etc

**Comment by stevengoldbergm** [comment]
Images have been sourced and color palette has been chosen. Animated icons/buttons have been developed, but some final scrolling animations still need to be added.
